# Generated by Django 3.1.2 on 2020-10-20 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('description_short', models.CharField(max_length=5000, verbose_name='Описание')),
                ('description_long', models.TextField(verbose_name='Полное описание')),
                ('lat', models.DecimalField(decimal_places=14, max_digits=16, verbose_name='Latitude')),
                ('lng', models.DecimalField(decimal_places=14, max_digits=16, verbose_name='Longitude')),
            ],
        ),
    ]
