# Generated by Django 3.1.2 on 2020-10-20 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0002_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='project',
            field=models.CharField(max_length=200, null=True, verbose_name='Проект'),
        ),
    ]
