# Generated by Django 3.1.2 on 2020-10-21 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0003_place_project'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='image',
            new_name='place_image',
        ),
    ]
