# Generated by Django 3.1.2 on 2020-10-27 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0008_auto_20201027_1648'),
    ]

    operations = [
        migrations.RenameField(
            model_name='place',
            old_name='project',
            new_name='title_short',
        ),
    ]
