# Generated by Django 3.1.2 on 2020-10-27 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0009_auto_20201027_1651'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='title_short',
            field=models.CharField(max_length=200, null=True, verbose_name='Краткое название'),
        ),
    ]
