# Generated by Django 3.1.2 on 2020-10-27 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0010_auto_20201027_1652'),
    ]

    operations = [
        migrations.RenameField(
            model_name='place',
            old_name='title_short',
            new_name='_short_title',
        ),
        migrations.RenameField(
            model_name='place',
            old_name='description_long',
            new_name='long_description',
        ),
        migrations.RenameField(
            model_name='place',
            old_name='description_short',
            new_name='short_description',
        ),
    ]
