# Generated by Django 3.1.2 on 2020-10-27 14:35

from django.db import migrations


def replace_null_to_empty(apps, schema_editor):
    Place = apps.get_model('places', 'Place') # noqa
    for place in Place.objects.all():
        place._short_title = place._short_title if place._short_title else '' # noqa
        place.save()


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0012_auto_20201027_1716'),
    ]

    operations = [
        migrations.RunPython(replace_null_to_empty),
    ]
