# Generated by Django 3.1.2 on 2020-10-27 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0013_auto_20201027_1735'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='_short_title',
            field=models.CharField(max_length=200, verbose_name='Краткое название'),
        ),
    ]
